const Types = {
  GET_QUIZ_SUCCESS: "GET_QUIZ_SUCCESS",
  GET_QUIZ_PENDING: "GET_QUIZ_PENDING",
  SET_NEXT_QUESTION: "SET_NEXT_QUESTION",
  INITIAL_STATE: "INITIAL_STATE",
  SELECT_ANSWER_SUCCESS: "SELECT_ANSWER_SUCCESS",
  START_QUIZ_ACTION: "START_QUIZ_ACTION",
  END_QUIZ_ACTION: "END_QUIZ_ACTION",
  VIEW_RESULTS_ACTION: "VIEW_RESULTS_ACTION",
};
export default Types;
